### ISSUE TITLE
Add public/artifacts to volumes in the docker-compose

### ISSUE THREAD

**Issue by matheusmota** [datasci4health/harena-manager#43]
It is a major problem, as the artifacts are saved in the /public

**Comment by matheusmota** [comment]
@santanche and @faguim, could you confirm the artifacts folder? Are we keeping the public/artifacts/*?

**Comment by faguim** [comment]
Yes. Is it necessary to change that location?

Em qui., 28 de nov. de 2019 às 23:38, Matheus Mota <notifications@github.com>
escreveu:
